# Generated by Django 4.1.2 on 2022-12-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBonos', '0002_dolar_delete_cantante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.DeleteModel(
            name='Concierto',
        ),
    ]
