# Generated by Django 4.1.2 on 2022-12-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBonos', '0004_pesoscer_alter_dolar_amortizacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PesosCer',
            new_name='Peso',
        ),
    ]
